### ISSUE TITLE
Updating test data

### ISSUE THREAD

**Issue by glv2** [ppcsuite/ppcd#2]
Some tests use test data, such as a raw block (blockchain/testdata/277647.dat.bz2), a txstore (blockchain/testdata/277647.txstore.bz2), etc.

For the tests to pass, the test data must be updated to contain data from the Peercoin blockchain instead of data from the Bitcoin blockchain as the block format is not the same.

Do you know if the original test data was generated with a tool of some kind, or if it was made by hand?

**Comment by mably** [comment]
kac- did most of the work on test data.  As far as I remember block data is stored in raw format (msgblock).  I guess he used some kind of home made tool to extract the wanted blocks from the ppcoin blockchain.  That would be very interesting to have such a tool to generate test data for sure.
How do you think we could do that?

**Comment by mably** [comment]
Block IO methods and functions in ppcoin:

Raw block data is stored in simple binary files:

https://github.com/ppcoin/ppcoin/blob/v0.4.0ppc/src/main.cpp#L798
https://github.com/ppcoin/ppcoin/blob/v0.4.0ppc/src/main.cpp#L2187
https://github.com/ppcoin/ppcoin/blob/v0.4.0ppc/src/main.h#L1072

Looks like the block index data is stored in a Berkeley database:

https://github.com/ppcoin/ppcoin/blob/v0.4.0ppc/src/db.h#L37
https://github.com/ppcoin/ppcoin/blob/v0.4.0ppc/src/db.h#L274
https://github.com/ppcoin/ppcoin/blob/v0.4.0ppc/src/db.cpp#L552

https://en.bitcoin.it/wiki/Data_directory

**Comment by mably** [comment]
The best way to generate test data might be making simple JSON/RPC calls to a running ppcoin client.
